title: "Enzo's Blog"
description: "Cyberpunk dreams, AI, and a path to elite cybersecurity."
baseurl: ""
url: "https://Enzo1612.github.io"
theme: null
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

