title: "Enzo's Blog"
description: "Cyberpunk dreams, AI, and a path to elite cybersecurity."
baseurl: ""
url: "https://Enzo1612.github.io"
theme: null
markdown: kramdown

# Add these lines for proper CSS handling
sass:
  sass_dir: _sass
  style: compressed

collections:
  bandit:
    output: true
    permalink: /bandit/:name

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
